GlobalPlanner:
  allow_unknow: True          # Specifies if the unknow grid cells should be use to plan the trajectory
  default_tolerance: 0.0      # Tolerance around the goal
  
  use_dijkstra: false         # If true, use Dijkstra's algorithm. Otherwise, use A*.
  use_quadratic: true         # If true, use the quadratic approximation of the potential. Otherwise, use a simpler calculation
  use_grid_path: true        # If true, create a path that follows the grid boundaries. Otherwise, use a gradient descent method
  old_navfn_behavior: false   # If true, the planner will mirror the behavior of navfn

  lethal_cost: 253            # Lethal cost (can be changed with dynamic reconfiguring)
  neutral_cost : 66           # Neutral Cost 
  cost_factor: 0.8            # Factor to multiply each cost from costmap by (can be changed with dynamic reconfiguring)

  publish_potential: true     # Publish Potential Costmap (can be changed with dynamic reconfiguring)

  orientation_mode: 0         # How to set the orientation of each point (None=0, Forward=1, Interpolate=2, ForwardThenInterpolate=3, Backward=4, Leftward=5, Rightward=6) (can be changed with dynamic reconfiguring)
  orientation_window_size: 1  # What window to use to determine the orientation based on the position derivative specified by the orientation mode
  outline_map: $(arg use_map) # Outlines the global costmap with lethal obstacles. For the usage of a non static (rolling window) global costmap this needs to be set to false