
#---(in meters)---
footprint: [ [-0.2325,-0.195], [0.2325,-0.195], [0.2325,0.195], [-0.2325,0.195] ]

map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 2.5
 raytrace_range: 3.0
 track_unknown_space: false
 footprint_clearing_enabled: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor:
    sensor_frame: $(arg robot_name)/rplidar
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true

inflation_layer:
  enabled:              true
  cost_scaling_factor:  30.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.7  # max. distance from an obstacle at which costs are incurred for planning paths.


