#---(in meters)---
footprint: [ [-0.3425,-0.195], [0.1425,-0.195], [0.1425,0.195], [-0.3425,0.195] ]

obstacle_layer:
 enabled: true
 obstacle_range: 2.5
 raytrace_range: 3.0
 track_unknown_space: false
 footprint_clearing_enabled: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor:
    sensor_frame: $(arg robot_name)/rplidar
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.5  # max. distance from an obstacle at which costs are incurred for planning paths.

staticmap_layer:
  unknow_cost_value: -1         # Value at which a map value is considered as unknown. If map doesn't use unknown, it will be considered occupied
  lethal_cost_threshold: 100    # Value at which a map value is considedred lethal. Lethal cells are avoided when planning
  track_unknown_space: false    # Set to true to translate the unknow values of the map in the costmap. Otherwise, unknown value will be considered as free space
  map_topic: "grid_map"              # Name of the map's topic. The map should be a nav_msgs/OccupancyGridMessage
  first_map_only: false         # Set to true to only use the first published map ignoring all other pulications
  subscribe_to_updates: false   # Set to true to use an additionnal map_tppic+"_updates"
  use_maximum: false            # Only matters if the static layer is not the bottom layer. If true, only the maximum value will be written to the master costmap.
  trinary_costmap: true         # Set to true to translate map with cells 3 states possible (NO_INFORMATION/FREE_SPACE/LETHAL_OBSTACLE). If false, intermediate values possible.
