# See here for documentation: http://wiki.ros.org/dwa_local_planner
DWAPlannerROS:

  # Robot Configuration Parameters
  max_vel_x: 0.3
  min_vel_x: -0.2

  max_vel_y: 0.0
  min_vel_y: 0.0

  # The velocity when robot is moving in a straight line
  max_vel_trans:  0.3
  min_vel_trans:  0.06

  # weirdly enough, parameters don't work with names given in documentation
  max_vel_theta: 1.0
  min_vel_theta: 0.05

  acc_lim_x: 0.6
  acc_lim_y: 0.0
  acc_lim_theta: 3.7

  # Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 40
  sim_granularity: 0.025
  controller_frequency: 20.0

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.15
  scaling_speed: 0.2
  max_scaling_factor: 0.2
  prune_plan: true

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.01

  # Debugging
  publish_traj_pc : false
  publish_cost_grid: true
