global_costmap:
  global_frame: $(arg robot_name)/map
  robot_base_frame: $(arg robot_name)/base_footprint
  update_frequency: 4.0
  publish_frequency: 3.0
  rolling_window: false
  width: 10.0
  height: 10.0
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
    - {name: staticmap_layer,     type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
