local_costmap:
  global_frame: $(arg robot_name)/odom
  robot_base_frame: $(arg robot_name)/base_footprint
  update_frequency: 10
  publish_frequency: 10
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.03  # Needs to be smaller than sim_time*min_vel_x/sqrt(2) 
  transform_tolerance: 0.5

  plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
