shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
#The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0,
# the global planner will only run when a new goal is received or the local planner reports that its path is blocked
# TODO, look if we should use 0.0 without global feeded map (only local)
planner_frequency: 1.0
oscillation_timeout: 15.0
oscillation_distance: 0.05
holonomic_robot: false