%YAML 1.1
---
packages:
    - swarmus_example_pkg
    - swarmus_ros_simulation
    - swarmus_ros_description
    - hive_mind
configurations:
    example:
        - swarmus_ros_simulation/launch/hive_mind_connector_dummy.launch
