global_costmap:
  global_frame: pioneer_0/odom
  robot_base_frame: pioneer_0/base_footprint
  update_frequency: 3.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  transform_tolerance: 0.5
