p_swarmus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  right_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_hinge
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  left_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_hinge
    pid: {p: 1000.0, i: 0.01, d: 10.0}


