name: ROS CI

on: [push, pull_request]

jobs:
  build-native:
    runs-on: ubuntu-20.04
    container:
      image: swarmus/embedded
    steps:
      - name: Create catkin_ws
        run: |
          mkdir -p catkin_ws/src
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          catkin_make_isolated

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'catkin_ws/src/SwarmUS-ROS'

      - name: Checkout submodules
        run: git submodule update --init --recursive
        working-directory: 'catkin_ws/src/SwarmUS-ROS'

      - name: Install ROS dependencies
        run: |
          rosdep update
          apt update
          rosdep install --from-paths src --ignore-src -r -y
        working-directory: 'catkin_ws'

      - name: Build
        run: |
          . ./devel_isolated/setup.sh
          catkin_make_isolated
        working-directory: 'catkin_ws'

      - name: Unit Tests (Hiveboard Bridge)
        run: |
          . ../../devel_isolated/setup.sh
          ctest -V
        working-directory: 'catkin_ws/build_isolated/hiveboard_bridge'
      
      - name: Check Format
        run: |
          python src/SwarmUS-ROS/tools/contrib/run-clang-format.py --recursive --style=file src/SwarmUS-ROS/src/
        working-directory: 'catkin_ws'