name: Haros Analysis

on: push

jobs:
  haros:
    runs-on: ubuntu-20.04
    container:
      image: swarmus/embedded
    steps:
      - name: Create catkin_ws
        run: |
          mkdir -p catkin_ws/src
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          catkin_make

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'catkin_ws/src/SwarmUS-ROS'

      - name: Checkout submodules
        run: git submodule update --init --recursive
        working-directory: 'catkin_ws/src/SwarmUS-ROS'

      - name: Install Haros
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          apt-get update && apt-get install -y python2 libmagic-dev
          wget https://bootstrap.pypa.io/get-pip.py
          python2 get-pip.py
          pip2 --version
          pip2 install haros

      - name: Run Haros
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          haros analyse -p src/SwarmUS-ROS/haros_config.yaml -b haros_plugin_radon haros_plugin_ccd haros_plugin_cppcheck haros_plugin_cpplint -n
          mkdir haros
          haros export -v ./haros
        working-directory: 'catkin_ws'

      - name: Prepare Publish Step
        run: |
          apt-get update && apt-get install -y rsync

      - name: Publish Result
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HAROS_VIZ_TOKEN }}
          external_repository: SwarmUS/Haros-viz
          publish_branch: gh-pages
          publish_dir: catkin_ws/haros
